defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: python:3-stretch

version: 2
jobs:
  verify:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Making report folder
          command: /bin/mkdir -p /tmp/PSO2es
      - run:
          name: Check for vaild JSONs
          command: ./_py/checkjson.py | /usr/bin/tee /tmp/PSO2es/checkjson.txt
      - store_artifacts:
          path: /tmp/PSO2es/
          destination: Reports

  tests:
    <<: *defaults
    steps:
      - run:
          name: Making report folder
          command: /bin/mkdir -p /tmp/PSO2es
      - checkout
      - run:
          name: Report Coverage
          command: /bin/sh ./_sh/coverage.sh | /usr/bin/tee /tmp/PSO2es/coverage.txt
      - run:
          name: Checking for item mapping
          command: ./_py/dupcheck.py | /usr/bin/tee /tmp/PSO2es/dupcheck.txt
      - run:
          name: Do we give the same name to 2+ entries?
          command: ./_py/dupassign.py | /usr/bin/tee /tmp/PSO2es/dupassign.txt
      - run:
          name: Checking if Dice Chat have too many lines
          command: ./_py/DiceLen.py | /usr/bin/tee /tmp/PSO2es/DiceLen.txt
      - run:
          name: Items' name too long for search box?
          command: ./_py/ItemLen.py | /usr/bin/tee /tmp/PSO2es/ItemLen.txt
      - run:
          name: Checking if Item Desc have too many lines
          command: ./_py/ItemDescLen.py | /usr/bin/tee /tmp/PSO2es/ItemDescLen.txt
      - run:
          name: Is JSON files Tidy?
          command: ./_py/tidy-json.py
      - run:
          name: Tidy changes
          command: /usr/bin/git diff --exit-code | /usr/bin/tee /tmp/PSO2es/tidy.diff
          when: on_fail
      - run:
          name: Apply Tidy changes
          command: /usr/bin/git add -u
          when: on_fail
      - run:
          name: Any text needs to by normalize?
          command: ./_tools/normalize.py | /usr/bin/tee /tmp/PSO2es/normalize.txt
      - run:
          name: Normalize changes
          command: /usr/bin/git diff --exit-code | /usr/bin/tee /tmp/PSO2es/normalize.diff
          when: on_fail
      - run:
          name: Apply normalize changes
          command: /usr/bin/git add -u
          when: on_fail
      - store_artifacts:
          path: /tmp/PSO2es/
          destination: Reports

  tests_font:
    <<: *defaults
    steps:
      - run:
          name: Making report folder
          command: /bin/mkdir -p /tmp/PSO2es
      - checkout
      - restore_cache:
          key: pip1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install Python packages
          command: pip install -r requirements.txt
      - save_cache:
          key: pip1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip
      - run:
          name: Is Story Buttons too big?
          command: ./_py/StoryBTNFont.py | /usr/bin/tee /tmp/PSO2es/StoryBTNFont.txt
      - run:
          name: Is Story text too big?
          command: ./_py/StoryFont.py | /usr/bin/tee /tmp/PSO2es/StoryFont.txt
      - run:
          name: Are Chips name too big?
          command: ./_py/ChipFont.py | /usr/bin/tee /tmp/PSO2es/ChipFont.txt
      - run:
          name: Are Chips' short Desc too long?
          command: ./_py/ChipDescShort.py | /usr/bin/tee /tmp/PSO2es/ChipDescShort.txt
      - run:
          name: Word wrap changes for Chips' Short Desc
          command: /usr/bin/git diff --exit-code | /usr/bin/tee /tmp/PSO2es/ChipDescShort.diff
          when: on_fail
      - run:
          name: Are Chips' long Desc too long?
          command: ./_py/ChipDescLong.py | /usr/bin/tee /tmp/PSO2es/ChipDescLong.txt
      - run:
          name: Word wrap changes for Chips' Long Descs
          command: /usr/bin/git diff --exit-code | /usr/bin/tee /tmp/PSO2es/ChipDescLong.diff
          when: on_fail
      - run:
          name: Apply word wrap changes
          command: /usr/bin/git add -u
          when: on_fail
      - run:
          name: Are the Dice Chat too big?
          command: ./_py/DiceFont.py | /usr/bin/tee /tmp/PSO2es/DictFont.txt
      - run:
          name: Are the Items' name too big?
          command: ./_py/ItemFont.py | /usr/bin/tee /tmp/PSO2es/ItemFont.txt
      - store_artifacts:
          path: /tmp/PSO2es/
          destination: Reports

  font_big:
    <<: *defaults
    steps:
      - run:
          name: Making report folder
          command: /bin/mkdir -p /tmp/PSO2es
      - checkout
      - restore_cache:
          key: pip1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install Python packages
          command: pip install -r requirements.txt
      - save_cache:
          key: pip1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip
      - run:
          name: Are the Items' Desc too big?
          command: ./_py/ItemDescFont.py | /usr/bin/tee /tmp/PSO2es/ItemDescFont.txt
      - run:
          name: Word wrap changes for Items' Descs
          command: /usr/bin/git diff --exit-code | /usr/bin/tee /tmp/PSO2es/ItemDescFont.diff
          when: on_fail
      - run:
          name: Apply changes
          command: /usr/bin/git add -u
          when: on_fail
      - store_artifacts:
          path: /tmp/PSO2es/
          destination: Reports

workflows:
  version: 2
  verify-test&build:
    jobs:
      - verify
      - build:
          requires:
            - verify
      - font_big:
          requires:
            - verify
      - tests_font:
          requires:
            - verify
      - tests:
          requires:
            - verify
